# Page settings

baseURL = "https://master.d3mopf4lwskvkv.amplifyapp.com/"
languageCode = "en"
title = "Jérémy Bulle - resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Jérémy Bulle"
    description = "Jérémy Bulle - Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Bulle Jérémy"
        tagline = "Engineer - Data Scientist - Machine learning engineer - Developer"
        avatar = "profile.jpg"

    [params.contact]
        enable = true
        location = "Belgium"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+32 493 31 96 83"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "jeremy.bulle@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "https://master.d3mopf4lwskvkv.amplifyapp.com/"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python developer"
        [[params.skills.list.items]]
        details = "AWS developer"
        [[params.skills.list.items]]
        details = "Machine learning/Artificial intelligence "
        [[params.skills.list.items]]
        details = "Data scienstis/Data Engineer"
        [[params.skills.list.items]]
        details = "Mechanical Engineer"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Skilled teacher"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Agile project management"
        [[params.skills.list.items]]
        details = "Customer oriented"
        [[params.skills.list.items]]
        [[params.skills.list]]
        title = "Soft skills"
        [[params.skills.list.items]]
        details = "Autonomous"
        [[params.skills.list.items]]
        details = "Resilient"
        [[params.skills.list.items]]
        details = "Determined"



    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Mechanical Engineering"
        university = "Ecole Polytechnique de Louvain"
        dates = "2005-2010"
        [[params.education.list]]
        degree = "Certificate in Artificial Intelligence"
        university = "Université polytechnique de Mons"
        dates = "2018"
        [[params.education.list]]
        degree = "Nanodegree in machine learning"
        university = "Udacity"
        dates = "2020"

    [params.interests]
        enable = true
        [[params.interests.list]]
        name = "Sport performance"
        [[params.interests.list]]
        name = "Neurosciences"
        [[params.interests.list]]
        name = "Global Human Performance"
        [[params.interests.list]]
        name = "Emerging technologies"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"
                [[params.languages.list]]
        name = "Dutch"
        level = "Basic"


    [params.summary]
        enable = true
        text = """ I started my career as a design engineer working as an effective contributor to Nuclear safety studies.
        I then took the responsibilities of technical coordinator, managing the interfaces between the involved departments on various projects.
        I was also responsible for drafting the severe accidents management guidelines for Tihange Nuclear power plants as well as teaching workshops and organizing full-scale training exercises on-site.
        I started expanding my skillset through self-learning about machine learning, deep learning and artificial intelligence.
        After an expatriation experience in UK on a Nuclear new-build project, I took new responsibilities as a data scientist in a team responsible for providing digital and data solutions  to internal customers.
        Nowadays, I manage digital projects in an Agile framework while still implementing technical solutions using data science, machine learning and cloud technologies such as AWS."""


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Digital enabler"
        dates = "2019 - Present"
        company = "Tractebel"
        [[params.experience.list.items]]
        details = "Providing technical insights leveraging business datasets"
        [[params.experience.list.items]]
        details = "Improving engineers' ways of working with data"
        [[params.experience.list.items]]
        details = "Developing digital applications"
        [[params.experience.list.items]]
        details = "Digital project management in an Agile framework"
        [[params.experience.list.items]]
        details = "Organizing and teaching workshops on data, digital tools, ..."

        [[params.experience.list]]
        title = "Lead severe accidents engineer"
        dates = "2016"
        company = "NuGeneration Limited"
        details = "Lead severe accidents engineer for the new-build Nuclear plant of Moorside using Westinghouse AP1000 technology"
        [[params.experience.list.items]]
        details = "Analysis the vendor's safety case regarding severe accidents"
        [[params.experience.list.items]]
        details = "Elaborating the roadmap for the severe accidents' operator safety case"
        [[params.experience.list.items]]
        details = "Reporting to the UK safety authorities (ONR)"

        [[params.experience.list]]
        title = "Design engineer"
        dates = "2010 - 2019"
        company = "Tractebel"
        [[params.experience.list.items]]
        details = "Responsible for probabilistic safety studies for Belgian Nuclear reactors"
        [[params.experience.list.items]]
        details = "Technical coordinator"
        [[params.experience.list.items]]
        details = "Owner of the severe accidents management guidelines for Tihange nuclear power plants"
        [[params.experience.list.items]]
        details = "Reporting to the Belgian safety authorities"





    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Analysis of the efficiency of parking sensors"
        meta = "Smart city"
        tagline = """Performed an analysis on two type of sensors (camera-based versus lidar-based) for the town of Angers to determine the most accurate sensor
        Project consisted of understanding raw data consisting of about 30 000 records, performing ETL operations and then translating the insights into actionnable conclusions for the project manager"""

        [[params.projects.list]]
        title = "Vizer"
        meta = "Industry 4.0"
        tagline = """Lead engineer on a project aiming to convert legacy technical drawings (PDF, paper) into industry 4.0 ready drawings leveraging modern computer vision techniques as well as deep learning. The project
        aimed at delivering a digital workbench to the engineers in order to increase their efficiency when working with technical drawings providing them with query, metadata, relationships between drawings and equipments 
        and a single place of truth. The platform also offered collaboration to the engineers to avoid duplicating the information and all the related issues."""

        [[params.projects.list]]
        title = "High performance Cloud computing"
        meta = "Cloud computing"
        tagline = """Project manager on two digital projects aiming to design cloud applications to provide engineers with an easy to use, state of the art and cost efficient HPC application for CFD workflows
        leveraging AWS capabilities such as low-maintenance, scalability and availability. The application also aimed at providing self-repair capabilities."""

        [[params.projects.list]]
        title = "Data science on miscellaneous business problems"
        meta = "Open data"
        tagline = """Participation to various open data challenges using the company open data platform e.g. analysis of wind turbines defects, buildings occupancy, solar panel production, ..."""

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2011 · Optimization of a U-Bend for Minimal Pressure Loss in Internal Cooling Channels: Part II—Experimental Validation"
        [[params.information.list.items]]
        details = "2011 · Optimization of a U-Bend for Minimal Pressure Loss in Internal Cooling Channels: Part  I—Numerical Method"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/FenryrMKIII"
        title = "FenryrMKIII"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/j%C3%A9r%C3%A9my-b-36223a20/"
        title = "Jérémy Bulle"





